# MPG Cars

### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd
import numpy as np

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

   ### Step 3. Assign each to a variable called cars1 and cars2

In [5]:
cars1 = pd.read_csv('cars1.csv')
cars2 = pd.read_csv('cars2.csv')
cars1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN

In [6]:
cars2.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,33.0,4,91,53,1795,17.4,76,3,honda civic
1,20.0,6,225,100,3651,17.7,76,1,dodge aspen se
2,18.0,6,250,78,3574,21.0,76,1,ford granada ghia
3,18.5,6,250,110,3645,16.2,76,1,pontiac ventura sj
4,17.5,6,258,95,3193,17.8,76,1,amc pacer d/l

### Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

In [8]:
cars1 = cars1.loc[:, : 'car']
cars1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino

### Step 5. What is the number of observations in each dataset?

In [9]:
cars1.shape, cars2.shape

((198, 9), (200, 9))

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [15]:
# cars = cars1.append(cars2) # was removed from pandas 2.0
cars = pd.concat([cars1, cars2], ignore_index= True)
# cars.shape
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97,52,2130,24.6,82,2,vw pickup
395,32.0,4,135,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120,79,2625,18.6,82,1,ford ranger
397,31.0,4,119,82,2720,19.4,82,1,chevy s-10

### Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [16]:
owners = np.random.randint(low = 15000, high = 73001, size = 398, dtype = 'l')
owners

array([50625, 43576, 62099, 53183, 33547, 17379, 17211, 70780, 20879,
       28665, 36899, 55131, 71116, 53522, 61982, 35834, 53818, 65759,
       60671, 19356, 21547, 64605, 57239, 24590, 31992, 69886, 36281,
       67703, 47651, 44502, 58222, 37497, 29683, 24744, 66019, 22532,
       71021, 63408, 70168, 19231, 16398, 43525, 52983, 52546, 71103,
       26279, 26940, 52959, 62513, 17530, 27970, 19725, 72849, 64322,
       53463, 63374, 69905, 49375, 54065, 50593, 31587, 61309, 31647,
       51313, 22566, 49415, 72469, 37684, 51667, 62336, 19112, 28465,
       19836, 42236, 65198, 58895, 19079, 53478, 23454, 65966, 61691,
       54384, 43532, 53647, 21501, 50270, 42876, 53136, 72965, 48889,
       39433, 71421, 51178, 58061, 23557, 39576, 43220, 55074, 34729,
       41087, 33340, 65079, 49275, 41643, 18531, 43097, 36163, 66034,
       50809, 38640, 52683, 53648, 60054, 22216, 22993, 23658, 49347,
       67006, 59093, 25547, 37101, 37552, 20049, 28893, 21740, 68868,
       37843, 32238, 52324, 49763, 23011, 34334, 72051, 27841, 21248,
       66676, 65491, 23866, 53024, 44254, 66806, 23005, 57829, 26140,
       29559, 36661, 59621, 71257, 67785, 19047, 34166, 34687, 41485,
       62416, 22678, 15049, 48441, 42718, 28136, 48736, 16876, 15681,
       51660, 70842, 39576, 34150, 36530, 29745, 54858, 49871, 31617,
       20068, 51909, 27370, 46830, 63761, 43945, 50349, 42075, 21651,
       48511, 37804, 28282, 21717, 38196, 66589, 26804, 44827, 24496,
       34674, 22750, 44841, 71341, 71039, 43494, 34145, 61157, 35172,
       64382, 68522, 15396, 42627, 35204, 22954, 58869, 54463, 59075,
       34495, 54054, 52732, 41602, 29315, 31137, 70690, 19320, 28837,
       21285, 26421, 29422, 46145, 38258, 49628, 28483, 68734, 54284,
       26794, 62945, 51959, 45924, 66749, 24095, 20693, 59563, 57640,
       41898, 39035, 59671, 34314, 48204, 68619, 57351, 16017, 33261,
       57512, 37419, 58148, 48951, 27848, 16026, 50006, 64463, 60959,
       43735, 47739, 23258, 27018, 50949, 17719, 17752, 68830, 56167,
       50891, 62219, 51268, 29287, 22759, 62335, 46906, 67733, 68530,
       56011, 32995, 32301, 53466, 51381, 47120, 65332, 70938, 33365,
       65371, 61580, 15053, 18588, 26759, 41419, 39225, 15145, 37745,
       29608, 62698, 50219, 45621, 37347, 70595, 16105, 47544, 71223,
       62936, 41774, 36683, 36065, 33084, 30239, 58253, 55330, 55729,
       52593, 49474, 29199, 43551, 51805, 48352, 33163, 38177, 24210,
       15513, 29997, 60269, 68983, 44849, 48834, 60578, 57283, 40668,
       29467, 46189, 68341, 18847, 21491, 28185, 43669, 16130, 61143,
       72981, 48725, 42679, 35770, 38906, 27129, 36269, 23780, 42825,
       16952, 51233, 53806, 57175, 41997, 61463, 18503, 20033, 18861,
       62902, 17824, 65456, 22069, 47740, 67177, 45539, 47361, 42714,
       37405, 56009, 33465, 26960, 67454, 47474, 64846, 15516, 67962,
       28188, 17306, 28974, 15414, 47596, 38621, 18372, 30046, 43356,
       58256, 16676, 24777, 53433, 27765, 51233, 35740, 51762, 60268,
       57090, 21461, 56627, 65699, 60040, 68063, 35878, 28003, 71357,
       58450, 20788])

### Step 8. Add the column owners to cars

In [17]:
cars['owner'] = owners
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owner
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,50625
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,43576
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,62099
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,53183
4,17.0,8,302,140,3449,10.5,70,1,ford torino,33547
...,...,...,...,...,...,...,...,...,...,...
393,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,35878
394,44.0,4,97,52,2130,24.6,82,2,vw pickup,28003
395,32.0,4,135,84,2295,11.6,82,1,dodge rampage,71357
396,28.0,4,120,79,2625,18.6,82,1,ford ranger,58450
397,31.0,4,119,82,2720,19.4,82,1,chevy s-10,20788