# Wine

### Introduction:

This exercise is a adaptation from the UCI Wine dataset.
The only pupose is to practice deleting data with pandas.

### Step 1. Import the necessary libraries

In [81]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data).

### Step 3. Assign it to a variable called wine

In [82]:
wine = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data')
wine.head()

,1,14.23,1.71,2.43,15.6,127,2.8,3.06,.28,2.29,5.64,1.04,3.92,1065
0,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
2,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
3,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
4,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450

### Step 4. Delete the first, fourth, seventh, nineth, eleventh, thirteenth and fourteenth columns

In [83]:
# type(wine.columns[0])
# wine.columns[[0,3,6,8,11,12,13]]

In [84]:
wine = wine.drop(wine.columns[[0,3,6,8,11,12,13]], axis = 1)
wine

     14.23  1.71  15.6  127  3.06  2.29   5.64
0    13.20  1.78  11.2  100  2.76  1.28   4.38
1    13.16  2.36  18.6  101  3.24  2.81   5.68
2    14.37  1.95  16.8  113  3.49  2.18   7.80
3    13.24  2.59  21.0  118  2.69  1.82   4.32
4    14.20  1.76  15.2  112  3.39  1.97   6.75
..     ...   ...   ...  ...   ...   ...    ...
172  13.71  5.65  20.5   95  0.61  1.06   7.70
173  13.40  3.91  23.0  102  0.75  1.41   7.30
174  13.27  4.28  20.0  120  0.69  1.35  10.20
175  13.17  2.59  20.0  120  0.68  1.46   9.30
176  14.13  4.10  24.5   96  0.76  1.35   9.20

[177 rows x 7 columns]

### Step 5. Assign the columns as below:

The attributes are (donated by Riccardo Leardi, riclea '@' anchem.unige.it):  
1) alcohol  
2) malic_acid  
3) alcalinity_of_ash  
4) magnesium  
5) flavanoids  
6) proanthocyanins  
7) hue

In [85]:
wine.columns = ['alcohol', 'malic_acid', 'alcalinity_of_ash', 'magnesium', 'flavanoids', 'proanthocyanins', 'hue']

In [86]:
wine

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,13.20,1.78,11.2,100,2.76,1.28,4.38
1,13.16,2.36,18.6,101,3.24,2.81,5.68
2,14.37,1.95,16.8,113,3.49,2.18,7.80
3,13.24,2.59,21.0,118,2.69,1.82,4.32
4,14.20,1.76,15.2,112,3.39,1.97,6.75
...,...,...,...,...,...,...,...
172,13.71,5.65,20.5,95,0.61,1.06,7.70
173,13.40,3.91,23.0,102,0.75,1.41,7.30
174,13.27,4.28,20.0,120,0.69,1.35,10.20
175,13.17,2.59,20.0,120,0.68,1.46,9.30
176,14.13,4.10,24.5,96,0.76,1.35,9.20

### Step 6. Set the values of the first 3 rows from alcohol as NaN

In [87]:
wine.iloc[:3, 0] = np.nan
wine.head()

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,1.78,11.2,100,2.76,1.28,4.38
1,NaN,2.36,18.6,101,3.24,2.81,5.68
2,NaN,1.95,16.8,113,3.49,2.18,7.80
3,13.24,2.59,21.0,118,2.69,1.82,4.32
4,14.20,1.76,15.2,112,3.39,1.97,6.75

### Step 7. Now set the value of the rows 3 and 4 of magnesium as NaN

In [88]:
wine.loc[[2, 3], 'magnesium'] = np.nan
wine.head()

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,1.78,11.2,100.0,2.76,1.28,4.38
1,NaN,2.36,18.6,101.0,3.24,2.81,5.68
2,NaN,1.95,16.8,NaN,3.49,2.18,7.80
3,13.24,2.59,21.0,NaN,2.69,1.82,4.32
4,14.20,1.76,15.2,112.0,3.39,1.97,6.75

### Step 8. Fill the value of NaN with the number 10 in alcohol and 100 in magnesium

In [ ]:
# wine.alcohol.fillna(10, inplace = True)
# wine.magnesium.fillna(100, inplace = True)
# wine.head()

/tmp/ipykernel_6502/1926234861.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  wine.alcohol.fillna(10, inplace = True)
/tmp/ipykernel_6502/1926234861.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  wine.magnesium.fillna(100, inplace = True)

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,1.78,11.2,100.0,2.76,1.28,4.38
1,NaN,2.36,18.6,101.0,3.24,2.81,5.68
2,NaN,1.95,16.8,NaN,3.49,2.18,7.80
3,13.24,2.59,21.0,NaN,2.69,1.82,4.32
4,14.20,1.76,15.2,112.0,3.39,1.97,6.75

In [92]:
wine['alcohol'] = wine['alcohol'].fillna(10)
wine['magnesium'] = wine['magnesium'].fillna(100)
wine

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,10.00,1.78,11.2,100.0,2.76,1.28,4.38
1,10.00,2.36,18.6,101.0,3.24,2.81,5.68
2,10.00,1.95,16.8,100.0,3.49,2.18,7.80
3,13.24,2.59,21.0,100.0,2.69,1.82,4.32
4,14.20,1.76,15.2,112.0,3.39,1.97,6.75
...,...,...,...,...,...,...,...
172,13.71,5.65,20.5,95.0,0.61,1.06,7.70
173,13.40,3.91,23.0,102.0,0.75,1.41,7.30
174,13.27,4.28,20.0,120.0,0.69,1.35,10.20
175,13.17,2.59,20.0,120.0,0.68,1.46,9.30
176,14.13,4.10,24.5,96.0,0.76,1.35,9.20

### Step 9. Count the number of missing values

In [96]:
wine.isnull().sum()

alcohol              0
malic_acid           0
alcalinity_of_ash    0
magnesium            0
flavanoids           0
proanthocyanins      0
hue                  0
dtype: int64

### Step 10.  Create an array of 10 random numbers up until 10

In [97]:
num_arr = np.random.randint(low = 0, high = 10, size = 10, dtype = 'l')
num_arr

array([6, 4, 4, 9, 4, 8, 7, 7, 6, 5])

### Step 11.  Use random numbers you generated as an index and assign NaN value to each of cell.

In [99]:
wine.loc[num_arr, 'alcohol'] = np.nan
wine.head()

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,10.00,1.78,11.2,100.0,2.76,1.28,4.38
1,10.00,2.36,18.6,101.0,3.24,2.81,5.68
2,10.00,1.95,16.8,100.0,3.49,2.18,7.80
3,13.24,2.59,21.0,100.0,2.69,1.82,4.32
4,NaN,1.76,15.2,112.0,3.39,1.97,6.75

### Step 12.  How many missing values do we have?

In [100]:
wine.isnull().sum()

alcohol              6
malic_acid           0
alcalinity_of_ash    0
magnesium            0
flavanoids           0
proanthocyanins      0
hue                  0
dtype: int64

### Step 13. Delete the rows that contain missing values

In [103]:
wine.dropna(inplace= True)
wine.isnull().sum()

alcohol              0
malic_acid           0
alcalinity_of_ash    0
magnesium            0
flavanoids           0
proanthocyanins      0
hue                  0
dtype: int64

### Step 14. Print only the non-null values in alcohol

In [108]:
mask = wine.alcohol.notnull()

In [109]:
wine.alcohol[mask]

0      10.00
1      10.00
2      10.00
3      13.24
10     14.12
       ...
172    13.71
173    13.40
174    13.27
175    13.17
176    14.13
Name: alcohol, Length: 171, dtype: float64

### Step 15.  Reset the index, so it starts with 0 again

In [110]:
wine.reset_index(inplace=True, drop= True)
wine

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,10.00,1.78,11.2,100.0,2.76,1.28,4.38
1,10.00,2.36,18.6,101.0,3.24,2.81,5.68
2,10.00,1.95,16.8,100.0,3.49,2.18,7.80
3,13.24,2.59,21.0,100.0,2.69,1.82,4.32
4,14.12,1.48,16.8,95.0,2.43,1.57,5.00
...,...,...,...,...,...,...,...
166,13.71,5.65,20.5,95.0,0.61,1.06,7.70
167,13.40,3.91,23.0,102.0,0.75,1.41,7.30
168,13.27,4.28,20.0,120.0,0.69,1.35,10.20
169,13.17,2.59,20.0,120.0,0.68,1.46,9.30
170,14.13,4.10,24.5,96.0,0.76,1.35,9.20

### BONUS: Create your own question and answer it.